---
- name: Generate directory path from name
  set_fact:
    hidden_service.dir: /var/lib/tor/{{ hidden_service.name }}
  when: hidden_service.dir is not defined

- name: Set the name from the directory
  set_fact:
    hidden_service.name: {{ hidden_service.dir }}
  when: hidden_service.name is not defined

- name: Generate directory for hidden service {{ hidden_service.name }}
  file:
    path: "{{ hidden_service.dir }}"
    owner: "{{ tor_user }}"
    group: "{{ tor_group }}"
    mode: 0700
    state: directory
